{
  imports = [
      ./barbar.nix
      ./bufferline.nix
      ./dashboard.nix
      ./lualine.nix
      ./neo-tree.nix
      ./noice.nix
      ./notify.nix
      ./nui.nix
      #./nvim-tree.nix
      ./oil.nix
      ./tagbar.nix
      ./telescope.nix
      ./toggleterm.nix
      ./treesitter.nix
      ./treesitter-context.nix
      #./virt-column-nvim.nix
      ./web-devicons.nix
  ];
}
